version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=cinnamon
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker_add:
    build: .
    command: celery -A app.worker.consumer worker --loglevel=info -Q add_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
  
  worker_subtract:
    build: .
    command: celery -A app.worker.consumer worker --loglevel=info -Q subtract_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
  
  worker_multiply:
    build: .
    command: celery -A app.worker.consumer worker --loglevel=info -Q multiply_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
  
  worker_divide:
    build: .
    command: celery -A app.worker.consumer worker --loglevel=info -Q divide_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker

  api:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app/app
    restart: always
