version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=cinnamon
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ocr_service:
    image: cinamonn/prj_flax:v1.9.0
    ports:
      - "8001:80"

  ocr_worker:
    build: .
    command: celery -A app.worker.celery_consumer worker --loglevel=info -Q ocr_queue
    volumes:
      - ./app/worker/:/app/app/worker
      - ./app/shared/:/app/app/shared
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

  ocr_api:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --log-config /app/app/logger/logger-config.yaml --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app/app
      - ./app/shared/:/app/app/shared
    env_file:
      - .env
    restart: always
    depends_on:
      - ocr_db
      - fs
      - ocr_service
      - ocr_worker

  fs:
    image: bitnami/minio:2023-debian-11
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: cinnamon
#    command: server /data --console-address ":9001"
    volumes:
      - file_storage_data:/data

  ocr_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cinnamon
      POSTGRES_DB: ocr_db
    volumes:
      - db_data:/var/lib/postgresql/data

  ocr_pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - ocr_db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinnamon.is
      PGADMIN_DEFAULT_PASSWORD: cinnamon
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
    file_storage_data:
        driver: local
    db_data:
        driver: local
    pgadmin_data:
        driver: local
