version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=cinnamon
    ports:
      - "5672:5672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker_add:
    build:
      context: ./app/worker
    command: celery -A app.worker.celery_consumer worker --loglevel=info -Q add_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
      - ./app/shared/:/app/app/shared
    env_file:
      - .env

  worker_subtract:
    build:
      context: ./app/worker
    command: celery -A app.worker.celery_consumer worker --loglevel=info -Q subtract_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
      - ./app/shared/:/app/app/shared
    env_file:
      - .env

  worker_multiply:
    build:
      context: ./app/worker
    command: celery -A app.worker.celery_consumer worker --loglevel=info -Q multiply_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
      - ./app/shared/:/app/app/shared
    env_file:
      - .env

  worker_divide:
    build:
      context: ./app/worker
    command: celery -A app.worker.celery_consumer worker --loglevel=info -Q divide_queue
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./app/worker/:/app/app/worker
      - ./app/shared/:/app/app/shared
    env_file:
      - .env

  api:
    build:
      context: ./app/api
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --log-config /app/app/shared/logger/logger-config.yaml --reload
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app/app
    env_file:
      - .env
    restart: always
